---
  - name: Install RPM with Satellite certificate
    yum:
      name: "{{ rhsm.cert_rpm }}"
      disable_gpg_check: true
      state: present
    when:
    - rhsm is defined
    - rhsm.cert_rpm is defined
  - name: Register with RHSM
    redhat_subscription:
      state: "{{ rhsm.state }}"
      server_hostname: "{{ rhsm.server_hostname }}"
      activationkey: "{{ rhsm.activationkey }}"
      org_id: "{{ rhsm.org_id }}"
      pool_ids: "{{ rhsm.pool_ids }}"
    when: rhsm is defined
    register: rhsm
  #- name: Show registration return value
  #  ansible.builtin.debug:
  #    msg: "{{ rhsm }}"
  - name: Install Katello agent
    yum:
      name:
        - katello-agent
        - insights-client
